name = "portlsignal"
compatibility_date = "2025-01-06"

main = "worker.js"

routes = [{ pattern = "portl.cam", custom_domain = true }]
assets = { directory = "./public/" }

[dev]
port = 8787

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "PORTAL_KV"
id = "dd32dbb082834438a2605347fac64675"
